### PR TITLE
adding more of my steps so I can ditch evernote

### PR DESCRIPTION
**Pull request by thesteve0**

### CODE REVIEW

**Comment by thesteve0** [comment]
@jorgemoralespou  you must have made changes before merging this request...

**Comment by jorgemoralespou** [comment]
I thought you merged it.
I will take a look ASAP and merge it.

I'm currently working on NFS volumes, as 1.1.3 was released yesterday.

**Comment by thesteve0** [comment]
Yeah saw that. Let's get NFL and exposed router before we ship

**Comment by thesteve0** [comment]
And by exposed router I mean exposed registry

**Comment by thesteve0** [comment]
Bump

**Comment by jorgemoralespou** [comment]
I did update this without PR, as I added some more things to it, so I'll close the PR.

The script can be run directly as root (it requires to be run as root), so if in user vagrant you need to sudo, or you can "sudo su -" to become root and execute the script.

At the end adds some notes (echoes to the terminal) with next steps.

If you need more, please, create a new PR, and I'll try not to screw it again.

**Comment by thesteve0** [comment]
But you left out some steps - please reopen and merge

**Comment by jorgemoralespou** [comment]
I don't see missing steps. Can you please rebase your merge in latest master. Then I will be able to know what you're talking about.
I've been looking for a while and the only thing I see missing is some comments "must run as root" which has been replaced by requiring root to run this script.

**Comment by jorgemoralespou** [comment]
This has already been clarified

**Pull request closed without merging**
