### PR TITLE
Fix #35: Install latest version of docker on centos.

### LINKED ISSUE #35: Old docker version on centos
The latest `centos` images that are pushed on hub.docker.com require at least docker engine 1.10 that supports schema version 2:

```
Downloading "https://github.com/iconoeugen/docker-nginx.git" ...
Step 1 : FROM centos@sha256:7b754086d2c7d74ac39dc0a2545d7b06d4266f873d502feb5b3e8bfca27c5dd8
Trying to pull repository docker.io/library/centos ... failed
error: build error: unsupported schema version 2 for tag "sha256:7b754086d2c7d74ac39dc0a2545d7b06d4266f873d502feb5b3e8bfca27c5dd8"
```

### PR DESCRIPTION
**Pull request by iconoeugen**
Removed docker package version specification for Centos yum install to install latest version available. Currently latest version of docker is 1.10, which support schema version 2.

### CODE REVIEW

**Comment by jfmatth** [comment]
Have you tested the Fedora Cloud version with the new docker?

**Comment by iconoeugen** [comment]
I have successfully tested with Fedora 24 and an older version of your
deployment. The problem with docker 1.10 is that it doesn't support storage
option 'dm.no_warn_on_loop_devices' (see:
https://github.com/docker/docker/issues/24161).

I'll do one more try to be sure and will remove WIP.

**Comment by iconoeugen** [comment]
Removed for docker 1.10 the unknown storage option "dm.no_warn_on_loop_devices" (see: docker/docker#24161).

**Comment by iconoeugen** [comment]
Does the restriction of docker version apply also for Fedora? This would be my first expectation as it is dependent of Openshift release version and not to the OS.

If this is the case, then it means that the current implementation has problems with Fedora as it installs always the latest version.

**Comment by jorgemoralespou** [comment]
@iconoeugen yes. I did not intend to maintain fedora, but John wanted to use it, so I leave the door open, and he's reporting issues there, that I will be eventually fixing. Feel free to solve it now.
So the issue at hand is being solved in origin master like 20 days ago, and hence will debut in 1.3.0-alpha.3
To make it easy I would just add the config to use latest docker, and if someone wants to build a previous release, the config would just set whatever version the user wants, leaving in the README a note that 1.9.1-25 is the one to use for those cases.
To be honest, once 1.3.0 is out, I don't expect people building previous releases, so this would be a temporary fix. Maybe not worth the effort and we can just use docker latest in there.
Do you build always latest or do you build releases?

**Comment by iconoeugen** [comment]
@jorgemoralespou I built always latest, but lately I have problems with it as I try to run a build config from Dockerfile which is using an image deployed in the internal openshift docker image registry and it always fails (looks like on Kubernetes side) to mount the secret volume. As I use for production [Telekom AppAgile](https://cloud.telekom.de/infrastruktur/appagile/) an managed Openshift deployment which is not wanted to keep the fast pace with the upstream, I need the possibility to test some older releases.

**Comment by jorgemoralespou** [comment]
@iconoeugen your issue should be probably reported in origin, as it looks more like an origin issue rather than a this VM thing.
If you still need to build and run old releases (which usually can be just pulled down from our atlas registry) then just add the ability to configure docker in legacy code. Thanks.

**Comment by iconoeugen** [comment]
@jorgemoralespou I have removed [WIP] as it's working fine for me now. As far as it goes for Fedora, there is only docker 1.10.3 available so the configuration value for docker version must be left empty to install the latest version.

**Pull request merged**
